GNU Radio's CDMA Package: gr::cdma::amp_var_est_impl Class Reference
gr::cdma::amp_var_est_impl Class Reference
#include <amp_var_est_impl.h>
Public Member Functions
float alpha () const
void set_alpha (float alpha)
amp_var_est_impl (float alpha)
~amp_var_est_impl ()
int work (int noutput_items, gr_vector_const_void_star &input_items, gr_vector_void_star &output_items)
Additional Inherited Members
Public Types inherited from gr::cdma::amp_var_est
typedef boost::shared_ptr< amp_var_est > sptr
Static Public Member Functions inherited from gr::cdma::amp_var_est
static sptr make (float alpha)
Return a shared_ptr to a new instance of cdma::amp_var_est.
Constructor & Destructor Documentation
gr::cdma::amp_var_est_impl::amp_var_est_impl (float alpha)
Referenced by set_alpha().
gr::cdma::amp_var_est_impl::~amp_var_est_impl ()
Referenced by set_alpha().
Member Function Documentation
float gr::cdma::amp_var_est_impl::alpha () const inline virtual
Implements gr::cdma::amp_var_est.
Referenced by set_alpha().
void gr::cdma::amp_var_est_impl::set_alpha (float alpha) inline virtual
Implements gr::cdma::amp_var_est.
References alpha(), amp_var_est_impl(), work(), and ~amp_var_est_impl().
int gr::cdma::amp_var_est_impl::work (int noutput_items, gr_vector_const_void_star & input_items, gr_vector_void_star & output_items)
Referenced by set_alpha().
The documentation for this class was generated from the following file:
amp_var_est_impl.h