GNU Radio's CDMA Package: gr::cdma::flag_gen_impl Class Reference
gr::cdma::flag_gen_impl Class Reference
#include <flag_gen_impl.h>
Public Member Functions
flag_gen_impl (int period, int acq)
~flag_gen_impl ()
int get_period () const
int get_acq () const
void set_acq (int acq)
int work (int noutput_items, gr_vector_const_void_star &input_items, gr_vector_void_star &output_items)
Additional Inherited Members
Public Types inherited from gr::cdma::flag_gen
typedef boost::shared_ptr< flag_gen > sptr
Static Public Member Functions inherited from gr::cdma::flag_gen
static sptr make (int period, int acq)
Return a shared_ptr to a new instance of cdma::flag_gen.
Constructor & Destructor Documentation
gr::cdma::flag_gen_impl::flag_gen_impl (int period, int acq)
gr::cdma::flag_gen_impl::~flag_gen_impl ()
Member Function Documentation
int gr::cdma::flag_gen_impl::get_acq () const inline
References set_acq(), and work().
int gr::cdma::flag_gen_impl::get_period () const inline
void gr::cdma::flag_gen_impl::set_acq (int acq) virtual
Implements gr::cdma::flag_gen.
Referenced by get_acq().
int gr::cdma::flag_gen_impl::work (int noutput_items, gr_vector_const_void_star & input_items, gr_vector_void_star & output_items)
Referenced by get_acq().
The documentation for this class was generated from the following file:
flag_gen_impl.h