GNU Radio's CDMA Package: gr::cdma::switched_peak_detector_fb_impl Class Reference
gr::cdma::switched_peak_detector_fb_impl Class Reference
#include <switched_peak_detector_fb_impl.h>
Public Member Functions
switched_peak_detector_fb_impl (float threshold_factor_rise, float threshold_factor_fall, int look_ahead, float alpha, int on)
~switched_peak_detector_fb_impl ()
void set_threshold_factor_rise (float thr)
void set_threshold_factor_fall (float thr)
void set_look_ahead (int look)
void set_alpha (float alpha)
void set_on (int on)
float threshold_factor_rise ()
float threshold_factor_fall ()
int look_ahead ()
float alpha ()
int on ()
int work (int noutput_items, gr_vector_const_void_star &input_items, gr_vector_void_star &output_items)
Additional Inherited Members
Public Types inherited from gr::cdma::switched_peak_detector_fb
typedef boost::shared_ptr< switched_peak_detector_fb > sptr
Static Public Member Functions inherited from gr::cdma::switched_peak_detector_fb
static sptr make (float threshold_factor_rise=0.25, float threshold_factor_fall=0.40, int look_ahead=10, float alpha=0.001, int on=1)
Return a shared_ptr to a new instance of cdma::switched_peak_detector_fb.
Constructor & Destructor Documentation
gr::cdma::switched_peak_detector_fb_impl::switched_peak_detector_fb_impl (float threshold_factor_rise, float threshold_factor_fall, int look_ahead, float alpha, int on)
gr::cdma::switched_peak_detector_fb_impl::~switched_peak_detector_fb_impl ()
Member Function Documentation
float gr::cdma::switched_peak_detector_fb_impl::alpha () inline virtual
Implements gr::cdma::switched_peak_detector_fb.
Referenced by set_alpha().
int gr::cdma::switched_peak_detector_fb_impl::look_ahead () inline virtual
Implements gr::cdma::switched_peak_detector_fb.
int gr::cdma::switched_peak_detector_fb_impl::on () inline virtual
Implements gr::cdma::switched_peak_detector_fb.
References work().
Referenced by set_on().
void gr::cdma::switched_peak_detector_fb_impl::set_alpha (float alpha) inline virtual
Implements gr::cdma::switched_peak_detector_fb.
References alpha().
void gr::cdma::switched_peak_detector_fb_impl::set_look_ahead (int look) inline virtual
Implements gr::cdma::switched_peak_detector_fb.
void gr::cdma::switched_peak_detector_fb_impl::set_on (int on) inline virtual
Implements gr::cdma::switched_peak_detector_fb.
References on().
void gr::cdma::switched_peak_detector_fb_impl::set_threshold_factor_fall (float thr) inline virtual
Implements gr::cdma::switched_peak_detector_fb.
void gr::cdma::switched_peak_detector_fb_impl::set_threshold_factor_rise (float thr) inline virtual
Implements gr::cdma::switched_peak_detector_fb.
float gr::cdma::switched_peak_detector_fb_impl::threshold_factor_fall () inline virtual
Implements gr::cdma::switched_peak_detector_fb.
float gr::cdma::switched_peak_detector_fb_impl::threshold_factor_rise () inline virtual
Implements gr::cdma::switched_peak_detector_fb.
int gr::cdma::switched_peak_detector_fb_impl::work (int noutput_items, gr_vector_const_void_star & input_items, gr_vector_void_star & output_items)
Referenced by on().
The documentation for this class was generated from the following file:
switched_peak_detector_fb_impl.h